### PR TITLE
Feature/design updates

### PR DESCRIPTION
**Pull request by kennethj**
More updates based on mock ups

### CODE REVIEW

**Comment by kennethj** [comment]
@jorahood  
Why is using the same file names bad? I know it is common in Java because you cannot alias imports, but that is not an issue with most other languages. I would argue `profile/profileStore.ts` is redundant. I would advocate for the shorter consistent names convention.

**Comment by jhoerr** [comment]
Andy, I think it's a reasonable objection but I tend to agree with Ken on this one. I'd prefer to not use filenames as a proxy for namespaces.

**Comment by jorahood** [comment]
I find it disorienting having multiple files with the same name just for development but I'm not adamant about it.
Could you run tests to generate a new contract with the changes in db.json before merging

**Comment by kennethj** [comment]
@jorahood is 89e09d6 good?

**Pull request merged**
