### PR TITLE
Feature/permissions

### PR DESCRIPTION
**Pull request by kennethj**
- [x]  Add a "Unit permissions" field to the add member form
- [x]  Add a "Unit permissions" field to the update member form

### CODE REVIEW

**Comment by jhoerr** [comment]
@kennethj Is this ready for review or still in progress?

**Comment by kennethj** [comment]
@jhoerr this is ready to go.

**Comment by jhoerr** [comment]
The way this works now, anyone who has privileges to manage a unit, can assign arbitrary permissions to any other unit member. Is that correct?

**Comment by kennethj** [comment]
Yes, currently if you can change the unit, you can update members and their unit permissions.

**Pull request merged**
